import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

/**
 * Blog content collection.
 * Posts are markdown/MDX committed to the repo (generated by Paul's own
 * pipeline). No third-party auto-publishing.
 */
const blog = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/blog' }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    // `slug` is optional: by default the URL comes from the filename.
    // Provide this only to override the generated slug.
    slug: z.string().optional(),
    publishDate: z.coerce.date(),
    // Target search query for the post.
    keyword: z.string(),
    // Topic cluster (e.g. "Presentation timers", "Focus / productivity").
    cluster: z.string(),
    // Optional social share image. TODO: per-post OG images.
    ogImage: z.string().optional(),
    draft: z.boolean().default(false),
  }),
});

export const collections = { blog };
